version: '2'
services:
  msprciapplication-app:
    image: msprciapplication
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://msprciapplication-postgresql:5432/msprCiApplication
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8341:8341
  msprciapplication-postgresql:
    extends:
      file: postgresql.yml
      service: msprciapplication-postgresql
